selection_wrap = false # wrap list if at bottom or top

[placeholders]
"default" = { input = "Search", list = "No Results" } # placeholders for input and empty list, key is the providers name, so f.e. "desktopapplications" or "menus:other"

[providers]
default = ["desktopapplications", "calc", "menus"]
empty = ["desktopapplications"]                    # providers to be queried when query is empty

[[providers.prefixes]]
prefix = "/"
provider = "files"

[[providers.prefixes]]
prefix = "."
provider = "symbols"

[[providers.prefixes]]
prefix = "!"
provider = "todo"

[[providers.prefixes]]
prefix = "="
provider = "calc"

[[providers.prefixes]]
prefix = "1"
provider = "clipboard"

[[providers.prefixes]]
prefix = "@"
provider = "archlinuxpkgs"

[providers.clipboard]
time_format = "%d.%m. - %H:%M" # format for the clipboard item date
